### ISSUE TITLE
gradleの対応バージョン

### ISSUE THREAD

**Issue by YuriCat** [miyo/geister_server.java#11]
gradleバージョン7系列ではビルドが失敗し、6系列では成功したので、
7以上に対応するか6以下限定だとREADMEに記載いただけると幸いです。

**Comment by miyo** [comment]
コメントありがとうございます．
7系に移行しようと思ったのですが，すんなりいかなかったので，
とりあえず6.8.3を使ってビルドしてもらうように追記しました．

**Comment by YuriCat** [comment]
ご返信、そしてご対応ありがとうございます！
こちらのgradle6.9.2でもビルドは成功していますので、6系列ならば大丈夫ではないかと思っています。

**Comment by miyo** [comment]
どうせ書くなら6.9.2がいいですね．というわけで記載修正しました．このIssueはクローズします．
