### ISSUE TITLE
HumanGUIPlayer画面のコマ描画のずれ (MacOSX, openjdk 17.0.2)

### ISSUE THREAD

**Issue by YuriCat** [miyo/geister_server.java#12]
手元のMacOSX、openjdk 17.0.2環境でHumanGUIPlayerを利用すると、
画像のように駒位置がずれて表示されます。
私の環境が想定環境と違っているのだと思いますが、環境依存が少ない解決法がもしございましたら、ありがたいです。

<img width="672" alt="スクリーンショット 2022-03-23 14 30 18" src="https://user-images.githubusercontent.com/8692100/159631095-d6312d35-2bec-4b07-8c89-56d90ff9b35e.png">

**Comment by miyo** [comment]
コメントありがとうございます．
現象としては，RetinaディスプレイなMacBookが発売されたときのRetinaディスプレイ未対応アプリのように見えます．
確認の意味で，使っているMacの型番とOSのバージョン番号もあわせて教えていただけますか？

盤面などは正しく表示されていますので，より適切なAPIで描画することで解決できるとは思うのですが...
こちらでの動作確認環境の準備含めて，少し時間ください．

**Comment by YuriCat** [comment]
ありがとうございます。
こちらでは2台のmacでずれを確認しています。

- モデルは2017年macbook(12インチ) OSはMonterey 12.3
- モデルは2018年macbook pro(13インチ) OSはCatalina 10.15.7 

openjdkは同じ17.0.2で、こちらはhomebrewで現時点で最新のものです。

**Comment by miyo** [comment]
情報ありがとうございます．こちらでも少し時間かかりそうですが試してみます．
ちなみに，JDK17とGradle 6系だとビルドできないと思っているのですが，そんなことなかったでしょうか？

**Comment by YuriCat** [comment]
手元では
Gradle 6.9.2
openjdk 17.0.2
でビルドできています。

**Comment by miyo** [comment]
MacBook 12"を入手して、連絡いただいた現象が発生することを確認できました。
対処方法はこれから探ります。

ところで、こちらの環境ですと、gradle 6.9.2とopenjdk 17.0.2の組み合わせですと、下記のようなエラーでビルドできません。何かオプションとか設定とかあるのでしょうか。教えていただけますと幸いです。

```
% gradle jar

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/miyo/geister_server.java/build.gradle'

* What went wrong:
Could not compile build file '/Users/miyo/geister_server.java/build.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 61
  
  java.lang.IllegalArgumentException: Unsupported class file major version 61
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:196)
...
```

**Comment by miyo** [comment]
dd6988a7299c27a2afe4ec086e13de8d014b6f4c で Retinaディスプレイ対応を試してみました。

```
git checkout issue-12
gradle jar
```

で対応版のチェックアウトとビルドをして、以下のように実行時の引数の最後に `gradle` というキーワードをつけて実行すると期待するような表示になると思います。

```
java -cp build/libs/geister.jar net.wasamon.geister.player.HumanGUIPlayer localhost 10001 ABCD retina
```

こちらの環境は、MacBook 12" 2017、OSはMontereyで、ディスプレイ解像度を変更してもうまく表示できることを確認しました。
ビルドはJava 11、実行はJava 17なので、もしかしたら挙動違うかもしれません。何かあれば教えていただければ、と。

**Comment by YuriCat** [comment]
ご対応ありがとうございます！ `retina` で正しい位置に描画されることを確認できました。

gradleの挙動をよくわかっていないのですが、ビルドのみ過去バージョンのjavaで行われているのかもしれません。
知人も同じ手順で動いていたので、その可能性に思い至りませんでした。

**Comment by miyo** [comment]
対応したコードを master ブランチにマージしたので，完了．

**Comment by miyo** [comment]
補足ですが，他のプロジェクトのビルドなどで `.gradle` や `$HOME/.gradle` にリソースが残っている場合には，gradle-6系+jdk17の組み合わせでもビルドできることがわかりました．
